WebApplicationSpiritualArt/Controllers/PrincipalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplicationSpiritualArt.Models;
using WebApplicationSpiritualArt.Logica_Negocio;

using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using Newtonsoft.Json;
using System.Threading.Tasks;
using WebApplicationSpiritualArt.Models.PagosPlan;
using System.IO;

namespace WebApplicationSpiritualArt.Controllers
{
    public class PrincipalController : Controller
    {
        LogicaNegocioArtista logicaNegocioArtista = new LogicaNegocioArtista();
        LogicaPlanes logicaPlanes = new LogicaPlanes();
        LogicaCategoria logicaCategoria = new LogicaCategoria();
        LogicaProductos logicaProductos = new LogicaProductos();
        // GET: Principal
        public ActionResult Index()
        {
            //listar obras de los artistas premium
            ViewBag.PremiumArtista = logicaProductos.listarObrasPremium();
            return View();
        }

        //este metodo es igual al index pero solo se accede a él cuando el artista se haya registrado(espacio virtual)
        public ActionResult IndexSesion()
        {
            //listar categorías
            List<CATEGORIA> categorias = logicaCategoria.listarCategoria();
            //consultar obras del artista
            int fk_artista = Convert.ToInt32( Session["id_registro"].ToString());
            ViewBag.ConsultaObras = logicaProductos.consultarObra(fk_artista);
            if (Session["correo"] != null && Session["clave"] != null)
            {
                return View(categorias);
            }
            else
            {
                return View("Index");
            }



        }
        //solo vista de registro
        public ActionResult RegistrarArtista()
        {
            List<TIPO_PLAN> listarPlanes = logicaPlanes.listarPlanes();
            return View(listarPlanes);
        }

        //registro de artista
        public ActionResult RegistrarArtistaAccion(REGISTRO_ARTISTA nuevoArtista)
        {

            TempData["correo"] = nuevoArtista.CORREO;
            TempData["nombre_artista"] = nuevoArtista.NOMBRE_ARTISTA;
            TempData["primer_apellido"] = nuevoArtista.PRIMER_APELLIDO_ARTISTA;
            TempData["segundo_apeliido"] = nuevoArtista.SEGUNDO_APELLIDO_ARTISTA;
            TempData["telefono"] = nuevoArtista.TELEFONO;
            TempData["pais"] = nuevoArtista.PAIS;
            TempData["ciudad"] = nuevoArtista.CIUDAD;
            TempData["localidad"] = nuevoArtista.LOCALIDAD;
            TempData["direccion"] = nuevoArtista.DIRECCION;
            TempData["fk_plan"] = nuevoArtista.FK_TIPO_PLAN;
            TempData["imagen"] = nuevoArtista.IMAGEN;
            int? fk_plan = nuevoArtista.FK_TIPO_PLAN;



            //verifica el tipo de plan
            if (nuevoArtista.FK_TIPO_PLAN == 8 || nuevoArtista.FK_TIPO_PLAN == 9)
            {
                TempData["correoRegistrado"] = nuevoArtista.CORREO;
                List<TIPO_PLAN> listarPlanes = logicaPlanes.listarPlanes(fk_plan);
                return View("OfertaPlanes", listarPlanes);
            }
            else
            {

                logicaNegocioArtista.RegistrarArtista(nuevoArtista);


                //consulta con varios parametros para traer la clave del artista
                REGISTRO_ARTISTA obtenerClave = logicaNegocioArtista.obtenerClaveArtista(nuevoArtista.CORREO, nuevoArtista.NOMBRE_ARTISTA, nuevoArtista.PRIMER_APELLIDO_ARTISTA, nuevoArtista.SEGUNDO_APELLIDO_ARTISTA);


                //envio de los parametros que va a llevar el envio del email
                logicaNegocioArtista.EnviarEmail(obtenerClave.CORREO, obtenerClave.CLAVE, obtenerClave.CORREO, obtenerClave.NOMBRE_ARTISTA);
                Session["id_registro"] = obtenerClave.PK_ID_ARTISTA;
                return View("IniciarSesionPago", obtenerClave);
            }
        }
        //solo vista de inicio de sesión
        public ActionResult IniciarSesion()
        {
            
            return View();
        }
        //vista que se muestra si el usuario relaizo el pago o se registró gratuitamente
        public ActionResult IniciarSesionPago()
        {
            string correo = TempData["correo"].ToString();
            string nombre_artista = TempData["nombre_artista"].ToString();
            string primer_apellido = TempData["primer_apellido"].ToString();
            string segundo_apellido = TempData["segundo_apeliido"].ToString();
            string telefono = TempData["telefono"].ToString();
            string pais = TempData["pais"].ToString();
            string ciudad = TempData["ciudad"].ToString();
            string localidad = TempData["localidad"].ToString();
            string direccion = TempData["direccion"].ToString();
            int? fk_plan = Convert.ToInt32(TempData["fk_plan"].ToString());
            string imagen = TempData["imagen"].ToString();

            var registrarArtista = new REGISTRO_ARTISTA()
            {
                NOMBRE_ARTISTA = nombre_artista,
                PRIMER_APELLIDO_ARTISTA = primer_apellido,
                SEGUNDO_APELLIDO_ARTISTA = segundo_apellido,
                TELEFONO = telefono,
                PAIS = pais,
                CIUDAD = ciudad,
                LOCALIDAD = localidad,
                DIRECCION = direccion,
                FK_TIPO_PLAN = fk_plan,
                CORREO = correo,
                IMAGEN = imagen


            };

            logicaNegocioArtista.RegistrarArtista(registrarArtista);

            REGISTRO_ARTISTA obtenerClave = logicaNegocioArtista.obtenerClaveArtista(correo, nombre_artista, primer_apellido, segundo_apellido);
            Session["id_registro"] = obtenerClave.PK_ID_ARTISTA;
            return View(obtenerClave);
        }
        //Acción al dar click en el botón iniciar sesión
        public ActionResult IniciarSesionAccion(REGISTRO_ARTISTA datosAcceso)
        {
            REGISTRO_ARTISTA acceso = logicaNegocioArtista.Acceso(datosAcceso);
            //listar categorías
            List<CATEGORIA> categorias = logicaCategoria.listarCategoria();
            
            if (acceso == null)
            {
                ViewBag.Mensaje = "Clave o usuario inválido, intente nuevamente";
                return View("IniciarSesion");
            }
            else if(acceso.ESTADO != true)
            {
                ViewBag.Mensaje = "Tu usuario actualmente está desactivado, comunicate con nosotros";
                return View("IniciarSesion");
            }
            else
            {
                Session["correo"] = acceso.CORREO;
                Session["clave"] = acceso.CLAVE;
                Session["imagen"] = acceso.IMAGEN;
                Session["ciudad"] = acceso.CIUDAD;
                Session["id_registro"] = acceso.PK_ID_ARTISTA;
                Session["pais"] = acceso.PAIS;
                Session["localidad"] = acceso.LOCALIDAD;
                Session["direccion"] = acceso.DIRECCION;
                Session["fk_plan"] = acceso.FK_TIPO_PLAN;
                Session["nombre_artista"] = acceso.NOMBRE_ARTISTA;
                Session["primer_apellido"] = acceso.PRIMER_APELLIDO_ARTISTA;
                Session["segundo_apellido"] = acceso.SEGUNDO_APELLIDO_ARTISTA;
                Session["telefono"] = acceso.TELEFONO;

                //consultar obras del artista
                int fk_artista = Convert.ToInt32(Session["id_registro"].ToString());
                ViewBag.ConsultaObras = logicaProductos.consultarObra(fk_artista);


                return View("IndexSesion", categorias);
            }
        }
        //vista donde el artista puede gestionar sus obras
        public ActionResult EspacioArtista()
        {
            return View();
        }

        //método que se usa para hacer el pago del plan desde paypal
        [HttpPost]
        public async Task<JsonResult> PagoPlan(string precio, string plan)
        {
            bool status = false;
            string respuesta = string.Empty;

            using (var client = new HttpClient())
            {
                var userName = "Aedtf_Rt5Y4MwJCsIph_C3re97TvnicO-cyxmTM_VRPsG1y-eUXREfVXpzPrhH1zZZkcNuRnb1QTYbmC";
                var password = "EFfc3lvPYwDO7FJBZuFg2BhZWb3EfUz-KLt_KfKKU_HzT1pHJPnG87BtMtlpopXbwJlSK-GGA5RaEqb7";

                client.BaseAddress = new Uri("https://api-m.sandbox.paypal.com");

                var authToken = Encoding.ASCII.GetBytes($"{userName}:{password}");
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", Convert.ToBase64String(authToken));

                var orden = new OrdenPlanes()
                {
                    intent = "CAPTURE",
                    purchase_units = new List<PurchaseUnit>()
                      {
                          new PurchaseUnit()
                          {
                              amount = new Amount()
                              {
                                  currency_code = "USD",
                                  value = precio
                              },
                              description = plan
                          }
                      },
                    application_context = new ApplicationContext()
                    {
                        brand_name = "SpiritualArt.com",
                        landing_page = "NO_PREFERENCE",
                        user_action = "PAY_NOW",
                        return_url = "https://localhost:44379/Principal/IniciarSesionPago",
                        cancel_url = "https://localhost:44379/Principal/Index"

                    }
                };

                var json = JsonConvert.SerializeObject(orden);
                var data = new StringContent(json, Encoding.UTF8, "application/json");

                HttpResponseMessage response = await client.PostAsync("/v2/checkout/orders", data);

WebApplicationSpiritualArt/Views/Principal/Exposicion.cshtml
@model List<WebApplicationSpiritualArt.Models.PRODUCTO>
@using WebApplicationSpiritualArt.Models
@{
    ViewBag.Title = "Exposicion";
    List<CATEGORIA> categorias = ViewBag.Categorias;
}

<h2>Exposicion</h2>
<form action="@Url.Action("FiltrarObras","Principal")" method="post">
    <label>Categoría de obra</label>
    <select name="id_categoria">
        @foreach (var Itemcategorias in categorias)
        {
            <option value="@Itemcategorias.PK_ID_CATEGORIA">@Itemcategorias.NOMBRE_CATEGORIA</option>
        }
    </select>
    <input type="submit" value="Buscar" />
</form>
<div class="container">
    <div class="rowProducts">
        <h2 class="titulocate">Obras que hacen parte de nuestra comunidad SpiritualArt</h2>
        <div class="row2">
            @foreach (var obras in Model)
            {

                <article class="">
                    <figure class="producto">
                        <img src="@Url.Content(obras.IMAGEN_PRODUCTO)">
                        <h2 class="subCate">@obras.PRECIO</h2>

                    </figure>

                </article>
            }

        </div>
    </div>
</div>

WebApplicationSpiritualArt/Views/Principal/Index.cshtml
@using WebApplicationSpiritualArt.Models
@{
    ViewBag.Title = "Index";
    List<PRODUCTO> listarObrasPremium = ViewBag.PremiumArtista;
}


<!-- carousel-->


<main>
    <section>
        <div class="lx">
            <div class="lx-row">
                <div class="lx-card carousel-container">
                    <div class="item fade">
                        <div class="image"><img src="~/ArchivosLectura/imagenes-index/imgs1.jpg" /></div>
                    </div>
                    <div class="item fade">
                        <div class="image"><img src="~/ArchivosLectura/imagenes-index/imgs1.jpg" /></div>
                        <div class="text ">
                            <h1 class="title"> <i class="far fa-hand-point-right"></i>&nbsp;This item has a title.</h1>
                            <p>This item has a caption, aligned to the left.</p>
                        </div>
                    </div>
                    <div class="item fade">
                        <div class="image"><img src="https://bit.ly/3iMHuI1" /></div>
                        <div class="text is-text-centered">
                            <p> <i class="fas fa-info-circle"></i>&nbsp;This item has a caption, aligned to the center.</p>
                        </div>
                    </div><a class="prev has-dflex-center"><i class="fas fa-angle-left"></i></a><a class="next has-dflex-center"><i class="fas fa-angle-right"></i></a>
                </div>
            </div>
        </div>
    </section>
</main>


<!--carousel 2-->


<div class="body2">
    <h2 class="titulocate">Obras Destacadas</h2>
    <div id="wrapper">
        <div id="carousel">
            <div id="content">
                @foreach (var obrasPremium in listarObrasPremium)
                {

                    <figure style="background-image:url(@obrasPremium.IMAGEN_PRODUCTO);">

                        <figcaption class="spn">
                            <a href="">@obrasPremium.NOMBRE_PRODUCTO</a>
                            <a href="">@obrasPremium.REGISTRO_ARTISTA.NOMBRE_ARTISTA</a>



                        </figcaption>

                    </figure>


                }


            </div>
        </div>
        <button id="prev">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path fill="none" d="M0 0h24v24H0V0z" />
                <path d="M15.61 7.41L14.2 6l-6 6 6 6 1.41-1.41L11.03 12l4.58-4.59z" />
            </svg>
        </button>
        <button id="next">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path fill="none" d="M0 0h24v24H0V0z" />
                <path d="M10.02 6L8.61 7.41 13.19 12l-4.58 4.59L10.02 18l6-6-6-6z" />
            </svg>
        </button>
    </div>



</div>
<div class="container">
    <div class="rowProducts">
        <h2 class="titulocate">Categorías</h2>
        <div class="row">
            <article class="">
                <figure class="producto">
                    <img src="~/ArchivosLectura/imagenes-index/pintura.jpg">
                    <h2 class="subCate">Pintura</h2>


                </figure>

            </article>

            <article class="">
                <figure class="producto">
                    <img src="~/ArchivosLectura/imagenes-index/escultura.jpg">
                    <h2 class="subCate">Escultura</h2>


                </figure>

            </article>

            <article class="">
                <figure class="producto">
                    <img src="~/ArchivosLectura/imagenes-index/lapiz.jpg">
                    <h2 class="subCate">Dibujo a lápiz</h2>


                </figure>

            </article>


            <article class="">
                <figure class="producto">
                    <img src="~/ArchivosLectura/imagenes-index/fotografia.jpg">
                    <h2 class="subCate">Fotografía</h2>


                </figure>

            </article>

        </div>
    </div>
</div>

WebApplicationSpiritualArt/Views/Principal/IndexSesion.cshtml
@model List<WebApplicationSpiritualArt.Models.CATEGORIA>
@using WebApplicationSpiritualArt.Models
@{
    ViewBag.Title = "IndexSesion";
    List<PRODUCTO> consultaObras = ViewBag.ConsultaObras;
}

<h2>IndexSesion</h2>

<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#AgregarObra">
    Agregar Obra
</button>
<br />
<br />


<!-- Modal -->
<div class="modal fade" id="AgregarObra" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Publicar Obra</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="@Url.Action("PublicarObraAccion","Principal")" method="post" enctype="multipart/form-data">
                <div class="modal-body">

                    <div class="in ">
                        <label>Nombre del obra</label>
                        <input class="form-control" type="text" name="NOMBRE_PRODUCTO" placeholder="Nombre de la obra" required />
                    </div>

                    <div class="in ">
                        <label>Precio</label>
                        <input class="form-control" type="number" name="PRECIO" placeholder="ingrese el precio" required />
                    </div>

                    <div class="in ">
                        <label>Descripción de la obra</label>
                        <input class="form-control" type="text" name="DESCRIPCION" required placeholder="Descripción" />
                    </div>

                    <div class="in ">
                        <label>Cantidad de esta obra</label>
                        <input class="form-control" type="number" name="CANTIDAD" required placeholder="Cantidad de la obra que quiere publicar" />
                    </div>

                    <div class="in ">
                        <label>Sube la imagen de tu obra</label>
                        <input class="form-control" type="file" name="archivoProducto" required />
                    </div>

                    <div class="in ">
                        <label>Selecciona la categoría de tu obra</label>
                        <select name="FK_CATEGORIA">
                            @foreach (var categorias in Model)
                            {
                                <option value="@categorias.PK_ID_CATEGORIA">@categorias.NOMBRE_CATEGORIA</option>
                            }
                        </select>
                    </div>

                    <input class="form-control" type="hidden" name="ESTADO" value="true" />
                    <input class="form-control" type="hidden" name="FK_ARTISTA" value="@Session["id_registro"]" />







                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    <input class="btn btn-primary" type="submit" name="name" value="Publicar" />
                </div>
            </form>
        </div>
    </div>
</div>
@if (consultaObras.Count >= 1)
{
    <div class="body2">
        <h2 class="titulocate">Mis Obras</h2>
        <div id="wrapper">
            <div id="carousel">
                <div id="content">
                    @foreach (var obras in consultaObras)
                    {


                        <figure style="background-image:url(@obras.IMAGEN_PRODUCTO);">

                            <figcaption class="spn"><a href="">@obras.NOMBRE_PRODUCTO</a></figcaption>

                        </figure>
                    }
                </div>
            </div>
            <button id="prev">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                    <path fill="none" d="M0 0h24v24H0V0z" />
                    <path d="M15.61 7.41L14.2 6l-6 6 6 6 1.41-1.41L11.03 12l4.58-4.59z" />
                </svg>
            </button>
            <button id="next">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                    <path fill="none" d="M0 0h24v24H0V0z" />
                    <path d="M10.02 6L8.61 7.41 13.19 12l-4.58 4.59L10.02 18l6-6-6-6z" />
                </svg>
            </button>
        </div>
   

    </div>
}
else
{
    <div>
        <h4>No tienes obras publicadas</h4>
    </div>
}

WebApplicationSpiritualArt/Views/Principal/IniciarSesion.cshtml
@{
    ViewBag.Title = "IniciarSesion";
}
<body class="body-sesion">

   

    <div class="cont">


        <form action="@Url.Action("IniciarSesionAccion","Principal")" method="post" class="form-sesion">


            <h2>Login</h2>


            <div class="in">
                <label>Usuario</label>
                <input class="form-control" type="text" name="CORREO" value="" placeholder="ingrese usuario" />
            </div>

            <div class="in">
                <label>Contraseña</label>
                <input class="form-control" type="password" name="CLAVE" value="" placeholder="Contraseña" />
            </div>

            <div class="in">

                <input class="btn btn-primary mt-4" type="submit" value="Ingresar" />



            </div>

            <div class="in">

                <h4 style="color:red">@ViewBag.Mensaje</h4>
                
            </div>

        </form>

    </div>

</body>

WebApplicationSpiritualArt/Views/Principal/IniciarSesionPago.cshtml
@model WebApplicationSpiritualArt.Models.REGISTRO_ARTISTA
@{
    ViewBag.Title = "IniciarSesion";
}

<body class="body-sesion">
<h2>IniciarSesion</h2>

<input type="text" value="@TempData["correoRegistrado"]" id="correo" hidden />



    <div class="cont">


        <form action="@Url.Action("IniciarSesionAccion","Principal")" method="post" class="form-sesion">


            <h2>Login</h2>


            <div class="in">
                <label>Usuario</label>
                <input class="form-control" type="text" name="CORREO" value="" placeholder="ingrese usuario" />
            </div>

            <div class="in">
                <label>Contraseña</label>
                <input class="form-control" type="password" name="CLAVE" value="" placeholder="Contraseña" />
            </div>

            <div class="in">

                <input class="btn btn-primary mt-4" type="submit" value="Ingresar" />



            </div>

            <div class="in">

                <h4 style="color:red">@ViewBag.Mensaje</h4>

            </div>

        </form>

    </div>

@if (Model.CLAVE != null)
{
    <script>
        var correo = document.getElementById("correo").value;

        alert("Hemos enviado el usuario y contraseña al correo: " + correo)
    </script>
}
</body>

WebApplicationSpiritualArt/Views/Principal/OfertaPlanes.cshtml
@model List<WebApplicationSpiritualArt.Models.TIPO_PLAN>
@{
    ViewBag.Title = "OfertaPlanes";
}

<h2>OfertaPlanes</h2>

@foreach (var planes in Model)
{
    if (planes.PRECIO != 0)
    {

        <div style="border:solid">
            <h3>@planes.NOMBRE_PLAN</h3><br />
            <input value="@planes.NOMBRE_PLAN" id="plan" hidden />
            <h3><label>Con un precio de:</label>@planes.PRECIO</h3><br />
            <input value="@planes.PRECIO" id="precio" hidden />
            <h3>@planes.DESCRIPCION_VISIBILIDAD</h3><br />
            <h3>@planes.DESCRIPCION_CANTIDAD_OBRAS</h3><br />
            <h3>@planes.DESCRIPCION_BUSQUEDA</h3><br />
            <h3>@planes.DESCRIPCION_TIEMPO_PLAN</h3><br />
        </div>
        <br />
        <br />
        <button onclick="pagar()">Contratar</button><br />
    }
}



@section scripts{

    <script>
        function pagar() {
            var body = {
                precio: $("#precio").val(),
                plan: $("#plan").val()



            }

            jQuery.ajax({

                url: '@Url.Action("PagoPlan","Principal")',
                type: "POST",
                data: JSON.stringify(body),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function (data) {

                    if (data.status) {

                        var jsonresult = JSON.parse(data.respuesta);

                        var links = jsonresult.links;

                        var resultado = links.find(item => item.rel === "approve")

                        window.location.href = resultado.href
                    } else {
                        alert("Intente más tarde")
                    }
                }
            });
        }


    </script>

}

WebApplicationSpiritualArt/Views/Principal/RegistrarArtista.cshtml
@model List<WebApplicationSpiritualArt.Models.TIPO_PLAN>

@{
    ViewBag.Title = "RegistrarArtista";

}


<body class="registro-body">

    <div class="cont">

        <form action="@Url.Action("RegistrarArtistaAccion","Principal")" method="post" class="form-registro">

            <input type="hidden" name="IMAGEN" value="~/ArchivosLectura/images.jpg" />

            <div>
                <h2 class="animate__animated animate__backInLeft">Registro</h2>
            </div>
            
            <div class="in ">
                <label>Nombre</label>
                <input class="form-control" type="text" name="NOMBRE_ARTISTA" placeholder="ingrese su nombre" required />
            </div>

            <div class="in ">

                <label>Primer Apellido</label>
                <input class="form-control" type="text" name="PRIMER_APELLIDO_ARTISTA" required placeholder="ingrese su apellido" />

            </div>

            <div class="in ">

                <label>Segundo Apellido</label>
                <input class="form-control" type="text" name="SEGUNDO_APELLIDO_ARTISTA" required placeholder="ingrese su segundo apellido" />

            </div>

            <div class="in ">

                <label>Teléfono</label>
                <input class="form-control" type="text" name="TELEFONO" required placeholder="ingrese su teléfono" />

            </div>

            <div class="in ">

                <label>Correo</label>
                <input class="form-control" type="email" name="CORREO" required placeholder="ingrese su email" />

            </div>

            <div class="in ">

                <label>País</label>
                <input class="form-control" type="text" name="PAIS" required placeholder="ingrese su país" />

            </div>

            <div class="in ">
                <label>Ciudad</label>
                <input class="form-control" type="text" name="CIUDAD" required placeholder="ingrese su ciudad" />
            </div>

            <div class="in ">
                <label>Localidad</label>
                <input class="form-control" type="text" name="LOCALIDAD" required placeholder="ingrese su localidad" />

            </div>

            <div class="in ">

                <label>Dirección</label>
                <input class="form-control" type="text" name="DIRECCION" required placeholder="ingrese su dirección" />

            </div>
            <div class="in ">

                <label>Tipo de plan</label>
                <select class="form-control" name="FK_TIPO_PLAN">
                    @foreach (var planes in Model)
                    {
                        <option value="@planes.PK_ID_TIPO_PLAN">@planes.NOMBRE_PLAN</option>
                    }

                </select>
            </div>

            <div>
                <input class="btn btn-primary mt-4" type="submit" value="Registrarse" />

            </div>

        </form>


    </div>

    
</body>